---

- name: install ftpserver
  hosts: all
  remote_user: ansible
  #become: yes
  #become_method: sudo
  #become_user: ansible

  tasks:
  - name: restart vsftp
    systemd:
      name: vsftpd.service
      state: restarted
    become: yes
    become_method: sudo
  #roles:
  #  - vsftp
