---

- name: install ftpserver
  hosts: all
  #remote_user: root
  become: true
  become_method: sudo

  tasks:
    - name: restart vsftp
      systemd:
        name: vsftpd.service
        state: restarted
  #roles:
  #  - vsftp
