---
- name: Install FTP server when host in ftpserver group
  ansible.builtin.yum:
    name: vsftpd
    state: latest
  ignore_errors: yes

- name: Enable vsftpd service
  ansible.builtin.systemd:
    name: vsftpd.service
    state: started
    enabled: yes
  ignore_errors: yes

- name: Install chrony server when host in ftpserver group
  ansible.builtin.yum:
    name: chrony
    state: latest
  ignore_errors: yes

- name: Enable chrony service
  ansible.builtin.systemd:
    name: chronyd.service
    state: started
    enabled: yes
