---
- name: Print out all variables on ask_limit_on_launch
  hosts: "{{ _hosts | default('localhost') }}"
  gather_facts: true
  vars:
    try_facts: "false"
    clear_facts: false
  tasks:

    - name: Set facts in sequence
      when: try_facts == true
      ansible.builtin.set_fact:
        fact_1: "{{ 1 | int }}"
        fact_2: "{{ fact_1 + 1 }}"
        fact_3: "{{ fact_2 + 1 }}"

    - name: Debug facts
      when: try_facts == true
      ansible.builtin.debug:
        msg:
          - "fact_1={{ fact_1 }}"
          - "fact_2={{ fact_2 }}"
          - "fact_3={{ fact_3 }}"


    - name: Show all variables
      ansible.builtin.debug:
        var: vars

    - name: Show inventory sources for this host
      debug:
        var: ansible_inventory_sources

    - name: Show group names for this host
      debug:
        var: group_names

    - name: Audit variables for every group this host belongs to
      ansible.builtin.debug:
        msg: "Group '{{ item }}' contains these variables: {{ hostvars[groups[item][0]] }}"
      loop: "{{ group_names }}"
      loop_control:
        label: "{{ item }}"

    - name: Show all variables
      ansible.builtin.debug:
        var: hostvars['localhost']
      when: "'ask_limit_on_launch' in hostvars['localhost']"

    - name: Clear the fact cache for this host
      when: clear_facts is true
      ansible.builtin.meta: clear_facts