---
- name: Accepting survey variables
  hosts: "{{ _hosts | split('\n')}}"
  vars:
    hosts_var: "{{ _hosts | split('\n')}}"
  tasks:
    - name: Print out the variable
      ansible.builtin.debug:
        msg: "{{ hosts_var }}"

    - name: Print out msg
      ansible.builtin.debug:
        msg: "Hey I just ran an action"
