---
galaxy_info:
  author: Todd Ruch
  description: Import Let's Encrypt certs into F5 BIG-IP and update SSL profiles
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions:
        - "9"
  galaxy_tags:
    - f5
    - bigip
    - ssl
    - tls
    - letsencrypt
    - certificate

dependencies: []
