---
- name: Do Something with Output
  hosts: all
  gather_facts: no

  tasks: 

  - name: "Set Variable for {{ inventory_hostname }}"
    set_fact:
      Host_Most_Secret_Password: '{{ (stage1_out |  selectattr("name", "search", inventory_hostname ) | list)[0].name }}'

  - name: "Print variable"
    debug:
      msg: 'Host: {{ inventory_hostname }}, Password: {{ Host_Most_Secret_Password }}"

