- name: Do Something with Output
  hosts: all
  gather_facts: no

  tasks: 

 - name: "Set Variable for Host"
    set_stats:
      data:
        Host_Most_Secret_Password: '{{ (stage1_out |  selectattr("name", "search", inventory_hostname ) | list)[0].name }}'
