- name: Do Something with Output
  hosts: all
  gather_facts: no
 
  # Print out variable
  - name: "Print variable"
    debug:
      #msg: "{{ servicenow_out }}"
      msg: '{{ (servicenow_out |  selectattr("name", "search", inventory_hostname ) | list)[0].name }}'
