---

- name: Get things from ServiceNow
  hosts: localhost
  gather_facts: no
  vars:
    #for all hosts
    url_string: '{{ SN_HOST }}/api/now/table/{{ SN_TABLE }}?sysparm_fields=name%2Cos%2Cfqdn'
    #for single host
    #url_string: '{{ SN_HOST }}/api/now/table/{{ SN_TABLE }}?sysparm_fields=name%2Cos&sysparm_limit=1&name={{ SN_SEARCH  }}'

  - name: Query ServiceNow API for host data
    uri:
      url: '{{ url_string }}'
      user: '{{ SN_USERNAME }}'
      password: '{{ SN_PASSWORD }}'
      method: GET
      force_basic_auth: yes
      headers:
        Content-Type: "application/json"
      body_format: json
    register: servicenow_response
    no_log: true

  # For all hosts in inventory
  - name: "Artifact URL of enable passing results in Tower Workflows"
    set_fact:
      servicenow_out: '{{ servicenow_response.json.result }}'
    no_log: true


  # Print out variable
  - name: "Print variable"
    debug:
      #msg: "{{ servicenow_out }}"
      msg: '{{ (servicenow_out |  selectattr("name", "search", "lnux100") | list)[0].name }}'


- name: Do Something with Output
  hosts: all
  gather_facts: no

  # Print out variable
  - name: "Print variable"
    debug:
      #msg: "{{ servicenow_out }}"
      msg: '{{ (servicenow_out |  selectattr("name", "search", inventory_hostname ) | list)[0].name }}'
