---

- name: Get things from ServiceNow
  hosts: localhost
  gather_facts: no
  vars:
    #for all hosts
    url_string: '{{ SN_HOST }}/api/now/table/{{ SN_TABLE }}?sysparm_fields=name%2Cos%2Cfqdn'
    #for single host
    #url_string: '{{ SN_HOST }}/api/now/table/{{ SN_TABLE }}?sysparm_fields=name%2Cos&sysparm_limit=1&name={{ SN_SEARCH  }}'

  tasks:
  - name: Display all variables/facts known for a host
    debug:
      var: hostvars[inventory_hostname]
    tags: debug_info
  
#  - name: Print some debug information 
#    vars: 
#      msg: |
#        Module Variables ("vars"):
#        --------------------------------
#        {{ vars | to_nice_json }} 
#    debug: 
#      msg: "{{ msg.split('\n') }}"       
#    tags: debug_info

  - name: Query ServiceNow API for host data
    uri:
      url: '{{ url_string }}'
      user: '{{ SN_USERNAME }}'
      password: '{{ SN_PASSWORD }}'
      method: GET
      force_basic_auth: yes
      headers:
        Content-Type: "application/json"
      body_format: json
    register: servicenow_response

# For individual host 
#  - name: print output
#    ansible.builtin.debug:
#      #msg: "{{ servicenow_out }}"
#      msg: "{{ servicenow_response.json.result[0].name }}"
#
#  - name: "Artifact URL of enable passing results in Tower Workflows"
#    set_stats:
#      data:
#        servicenow_out: "{{ servicenow_response.json.result[0].name }}"

# For all hosts in inventory
  - name: "Artifact URL of enable passing results in Tower Workflows"
    set_stats:
      data:
        servicenow_out: "{{ servicenow_response.json.result }}"

