---
- name: Copy file from remote windows host to windows host
  hosts: "{{ _win_host1 }}"
  gather_facts: false
  tasks:

    - name: Create some content on the remote windows host
      ansible.windows.win_copy:
        dest: C:\Users\ec2-user\Desktop\example.txt
        content: "This is an example file."

    - name: Fetch file from remote windows host
      ansible.builtin.fetch:
        src: C:\Users\ec2-user\Desktop\example.txt
        dest: /tmp/example.txt
        flat: yes

    - name: Tail the end of example.txt
      delegate_to: localhost
      ansible.builtin.command: tail -n 10 /tmp/example.txt
      register: tail_output

    - name: Display the tail output
      delegate_to: localhost
      ansible.builtin.debug:
        var: tail_output.stdout_lines
        verbosity: 2

    - name: Copy file from win host 1 to win host 2
      delegate_to: "{{ _win_host2 }}"
      ansible.builtin.copy:
        src: /tmp/example.txt
        dest: C:\Users\ec2-user\Desktop\example.txt
