---
- name: Copy file from remote windows host to linux host
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Print out variables
      delegate_to: localhost
      ansible.builtin.debug:
        msg: >
          User: {{ copy_username | default('Not provided') }}
          Password: {{ copy_password | default('Not provided') }}
          SSH Key: {{ copy_ssh_key_data | default('Not provided') }}

    - name: Copy file from windows to linux
      vars:
        ansible_user: "{{ copy_username | default(omit) }}"
        ansible_password: "{{ copy_password | default(omit) }}"
        ansible_ssh_key_data: "{{ copy_ssh_key_data | default(omit) }}"
      ansible.builtin.ping:
