---

- name: apply MOTD to all nodes
  hosts: all
  remote_user: truch
  become: true

  tasks:
    - ping:

    - name: Display all variables/facts known for a host
      ansible.builtin.debug:
        var: hostvars[inventory_hostname]

  roles:
    - motd
