---
- name: "Get current input source from the API"
  ansible.builtin.set_fact:
    credential_input_sources_lookvar: "{{ query(controller_api_plugin, 'api/controller/v2/credentials/' + __credential_id + '/input_sources/',
                                  host=aap_hostname, oauth_token=aap_oauthtoken, verify_ssl=aap_validate_certs,
                                  return_all=true, max_objects=query_controller_api_max_objects)
                         }}"
  vars:
    __credential_id: "{{ current_credential['id'] }}"
  no_log: "{{ controller_configuration_filetree_create_secure_logging }}"

- name: "Block for to generate flatten output"
  when:
    - flatten_output is defined
    - flatten_output | bool
    - credential_input_sources_lookvar | length > 0
  vars:
    __dest: "{{ output_path }}/controller_credential_input_sources.yaml"
  block:
    - name: "Stat if the output file exists"
      ansible.builtin.stat:
        path: "{{ __dest }}"
      register: credential_input_source_file

    - name: "Add current credential input source to the flat file"
      ansible.builtin.blockinfile:
        create: true
        mode: "0644"
        insertafter: EOF
        path: "{{ __dest }}"
        marker: ""
        block: "{{ lookup('template', 'templates/controller_credential_input_sources.j2') }}"
      vars:
        first_credential_input_source: "{{ not credential_input_source_file.stat.exists }}"
      when: credential_input_sources_lookvar | length > 0

    - name: "Remove all the blank lines introduced by the last task"
      ansible.builtin.lineinfile:
        path: "{{ __dest }}"
        line: ''
        state: absent

- name: "Block for to generate the filetree_create normal output"
  when:
    - flatten_output is not defined or not (flatten_output | bool)
    - credential_input_sources_lookvar | length > 0
  block:
    - name: "Create the output directory for controller_credential_input_sources: {{ output_path }}"
      ansible.builtin.file:
        path: "{{ normal_path }}/controller_credential_input_sources"
        state: directory
        mode: '0755'

    - name: "Add current credential input sources to the output yaml file"
      ansible.builtin.template:
        src: "templates/controller_credential_input_sources.j2"
        dest: "{{ normal_path }}/controller_credential_input_sources/controller_credential_input_sources_{{ current_credential['name'] | regex_replace('/', '_') }}.yaml"
        mode: '0644'
      when: credential_input_sources_lookvar | length > 0
...
