---
- name: Import file tree into controller
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    controller_username: "{{ vault_controller_username | default(lookup('env', 'CONTROLLER_USERNAME')) }}"
    controller_password: "{{ vault_controller_password | default(lookup('env', 'CONTROLLER_PASSWORD')) }}"
    controller_hostname: "{{ vault_controller_hostname | default(lookup('env', 'CONTROLLER_HOST')) }}"
    controller_validate_certs: "{{ vault_controller_validate_certs | default(lookup('env', 'CONTROLLER_VERIFY_SSL')) }}"
    aap_username: "{{ vault_aap_username | default(lookup('env', 'CONTROLLER_USERNAME')) }}"
    aap_password: "{{ vault_aap_password | default(lookup('env', 'CONTROLLER_PASSWORD')) }}"
    aap_hostname: "{{ vault_aap_hostname | default(lookup('env', 'CONTROLLER_HOST')) }}"
    aap_validate_certs: "{{ vault_aap_validate_certs | default(lookup('env', 'CONTROLLER_VERIFY_SSL')) }}"
    import_path: "./export_ft6"

  pre_tasks:
    - name: "Setup authentication (block)"
      when: controller_oauthtoken is not defined
      block:
        - name: "Get the Authentication Token for the future requests"
          ansible.builtin.uri:
            url: "https://{{ controller_hostname }}/api/gateway/v1/tokens/"
            user: "{{ controller_username }}"
            password: "{{ controller_password }}"
            method: POST
            force_basic_auth: true
            validate_certs: "{{ controller_validate_certs }}"
            status_code: 201
          register: authtoken_res

        - name: "Set the oauth token to be used since now"
          ansible.builtin.set_fact:
            controller_oauthtoken: "{{ authtoken_res.json.token }}"
            aap_token: "{{ authtoken_res.json.token }}"
            controller_oauthtoken_url: "{{ authtoken_res.json.url }}"

  tasks:
    # - name: Include configuration info for credential types
    #   ansible.builtin.include_vars: "{{ import_path }}/current_credential_types.yaml"
      # ansible.builtin.include_vars: "{{ import_path }}/current_credential_types.yaml"


    - name: Include all .yaml files from the import_path
      ansible.builtin.include_vars:
        dir: '{{ import_path }}'
        ignore_files:
          - 'controller_settings.yaml'
          - 'current_settings.yaml'
          - 'controller_settings.yaml'
          - 'eda_credential_types.yaml'
          - 'gateway_service_keys.yaml'
        extensions:
          - 'yaml'
        depth: 1

    - name: Dispatch the configuration to AAP 2.5
      ansible.builtin.include_role:
        name: infra.aap_configuration.dispatch
      vars:
        controller_configuration_filetree_create_secure_logging: false
        controller_configuration_filetree_read_secure_logging: false
        aap_configuration_secure_logging: false
        aap_configuration_collect_logs: false
        cas_secure_logging: false

  post_tasks:
    - name: "Delete the Authentication Token used"
      ansible.builtin.uri:
        url: "https://{{ controller_hostname }}{{ controller_oauthtoken_url }}"
        user: "{{ controller_username }}"
        password: "{{ controller_password }}"
        method: DELETE
        force_basic_auth: true
        validate_certs: "{{ controller_validate_certs }}"
        status_code: 204
      when: controller_oauthtoken_url is defined

...
