---
- name: Patching Rescue Example Playbook
  hosts: all
  gather_facts: true
  vars:
    success_nodes: []
    failure_nodes: []
  tasks:
    - block:
        - name: Simulate a task that may fail by assert that ansible_distribution_major_version == 9
          ansible.builtin.assert:
            that:
              - ansible_distribution_major_version == "9"
            fail_msg: "This task simluates a failure in a playbook that we want to recover from."
            success_msg: "This host passed the test"

        - name: Add successful nodes to succes list
          delegate_to: localhost
          ansible.builtin.set_fact:
            success_nodes = "{{ success_nodes + [inventory_hostname] }}"
      rescue:
        - name: Add failure nodes to failure list
          delegate_to: localhost
          ansible.builtin.set_fact:
            failure_nodes = "{{ failure_nodes + [inventory_hostname] }}"
      # always:
      #   - <always_task>
    - name: Create dictionary to pass to follow-on nodes
      ansible.builtin.set_stats:
        data:
          _success_nodes: "{{ success_nodes }}"
          _failure_nodes: "{{ failure_nodes }}"


...
