---

- name: Find RHEL servers and set as a dynamic limit
  hosts: [aws_rhel8, aws_rhel9]
  become: true
  gather_facts: true
  
  tasks:
    - name: Create a group of just the RHEL hosts
      ansible.builtin.group_by:
        key: rhel_hosts
      when: ansible_facts['os_family'] == "RedHat"

    - name: Create a comma-separated string of hostnames
      ansible.builtin.set_fact:
        # The join(',') filter is key here, creating a string like "web01,web03,web04"
        limit_string: "{{ groups['rhel_hosts'] | join(',') }}"
      run_once: true

    - name: Set the dynamic limit as a workflow artifact
      ansible.builtin.set_stats:
        data:
          # This variable 'dynamic_limit_hosts' will be available to downstream nodes
          dynamic_limit_hosts: "{{ limit_string }}"
      run_once: true
