---

- name: get contents of authorized_keys
  hosts: all
  become: true
  gather_facts: false

  tasks:
    #- name: Get contents of authorized_keys 
    #  shell: cat /root/.ssh/authorized_keys
    #  register: pb1_contents

    - name: Find out what the remote machine's mounts are
      ansible.builtin.slurp:
        src: /home/ec2-user/.ssh/authorized_keys
      register: program_conf

    - name: Set Fact from returned information
      ansible.builtin.set_fact:
        auth_keys: "{{ (program_conf['content'] | b64decode).split('\n') }}"

    - name: Print returned information
      ansible.builtin.debug:
        var: auth_keys
        verbosity: 2

    - name: "Artifact URL of test results to Tower Workflows"
      set_stats:
      per_host: true
        data:
          auth_keys_results: "{{ auth_keys }}"

