---

- name: print contents of authorized_keys
  hosts: all
  gather_facts: false

  tasks:
    - name: print contents of authorized_keys from PB1
      debug: msg="pb2 - the value of pb1_contents is {{ auth_keys_results }}"

