---
all:
  children:
    virtana:
      hosts:
        virtana01.example.com:
          ansible_host: 10.1.1.60
          ansible_user: virtadmin
        virtana02.example.com:
          ansible_host: 10.1.1.61
          ansible_user: virtadmin
