---
collections:
  - name: f5networks.f5_modules
    version: ">=1.32.0"
  - name: ansible.netcommon
  - name: community.crypto
  - name: community.general
  - name: amazon.aws
    version: ">=9.0.0"
