---
# The vm_memory_mb and vm_num_cpus variables can be passed at runtime and must be larger then current resources or will error out
# ansible-navigator run -mstdout vmware_hotadd.yml -vv --eei=quay.io/sdunnesa/ee-sdunne:1.10 -e vm_memory_mb=8192 -e vm_num_cpus=4

- name: Hot add resources to VMware VM in vCenter
  hosts: localhost
  gather_facts: false

  tasks:
    - name: VMware hotadd resources
      ansible.builtin.import_role:
        name: cloud.vmware_ops.provision_vm
      vars:
        provision_vm_hostname: "{{ vcenter_hostname | default(omit) }}"
        provision_vm_username: "{{ vcenter_username | default(omit) }}"
        provision_vm_password: "{{ vcenter_password | default(omit) }}"
        provision_vm_cluster: "Cluster-1"
        provision_vm_datacenter: "SDDC-Datacenter"
        provision_vm_folder: "Workloads/{{ vcenter_folder }}"
        provision_vm_name: "{{ vm_name }}"
#        provision_vm_template: "{{ vm_template }}"
#        provision_vm_port: "8989"
#        provision_vm_disk:
#        - size_gb: 10
#          type: thin
#          datastore: "LocalDS_0"
        provision_vm_hardware:
          hotadd_memory: true
          memory_mb: "{{ vm_memory_mb | default(omit) }}"
          hotadd_cpu: true
          num_cpus: "{{ vm_num_cpus | default(omit) }}"