# ssh_key is defined in the 'all' group in inventory, so it is inherited by all hosts
# it can be overridden in a specific host or group (it is overridden in the acc group)


- name: "Add authorized keys"
  ansible.posix.authorized_key:
    user: ansible
    key: "{{ item }}"
    state: present
  loop: "{{ ssh_keys | default([ssh_key]) }}"
  when: ssh_keys is defined or ssh_key is defined

- name: "Remove unauthorized key"
  ansible.posix.authorized_key:
    user: ansible
    key: "{{ epcot_cluster_pubkey }}"
    state: absent
  when: inventory_hostname not in groups['type_epcotodb'] and epcot_cluster_pubkey is defined

- name: Print out SSH Keys
  ansible.builtin.debug:
    msg: "SSH Keys for {{ inventory_hostname }}: {{ ssh_keys | default([ssh_key]) }}"
  when: ssh_keys is defined or ssh_key is defined
