---
- name: Generate and Email System Report
  hosts: your_target_servers # Replace with your inventory group or hostname (e.g., 'webservers')
  gather_facts: true         # Gather system facts for the report
  connection: ssh            # Or 'winrm' for Windows hosts, 'local' if running against localhost

  # Define variables for email configuration and report content
  vars:
    # -- Email Settings --
    mail_server: "smtp.example.com" # Replace with your SMTP server address
    mail_port: 587                  # Standard SMTP TLS port (587) or SSL (465)
    mail_username: "your_email@example.com" # Replace with your sending email address
    mail_password: "your_email_password" # IMPORTANT: Use Ansible Vault for this!
    mail_from: "Ansible_Reporter <ansible@yourdomain.com>" # Sender display name and email
    mail_to: "recipient@example.com" # Recipient email address
    mail_subject: "Ansible System Report - {{ ansible_hostname }} - {{ ansible_date_time.date }}"

    # -- Report Content Variables --
    report_header: |
      System Report for Host: {{ ansible_hostname }}
      Generated On: {{ ansible_date_time.date }} at {{ ansible_date_time.time }}

      --- System Information ---
      OS: {{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_os_family }})
      Kernel: {{ ansible_kernel }}
      Architecture: {{ ansible_architecture }}
      Memory: {{ ansible_memtotal_mb }} MB
      CPU Cores: {{ ansible_processor_vcpus }}

      --- Disk Usage ---
    report_footer: |
      --- End of Report ---
      This report was automatically generated by Ansible.

  tasks:
    - name: Ensure community.general collection is installed
      ansible.builtin.command: ansible-galaxy collection install community.general
      args:
        creates: ~/.ansible/collections/ansible_collections/community/general
      delegate_to: localhost
      run_once: true
      changed_when: false
      failed_when: false
      # This task ensures the 'community.general' collection is present, which contains the 'mail' module.
      # In a production environment, you'd typically manage collection dependencies in a requirements.yml file.

    - name: Get disk usage information
      ansible.builtin.shell: df -h
      register: disk_usage_output
      changed_when: false # This command doesn't change anything, so mark as not changed

    - name: Construct the full report body
      ansible.builtin.set_fact:
        full_report_body: |
          {{ report_header }}

          {{ disk_usage_output.stdout }}

          {{ report_footer }}

    - name: Send the report via email
      community.general.mail:
        host: "{{ mail_server }}"
        port: "{{ mail_port }}"
        username: "{{ mail_username }}"
        password: "{{ mail_password }}"
        from: "{{ mail_from }}"
        to: "{{ mail_to }}"
        subject: "{{ mail_subject }}"
        body: "{{ full_report_body }}"
        secure: starttls # Use 'ssl' for port 465, 'starttls' for port 587
        # You might need to add 'validate_certs: false' if using a self-signed certificate
        # for your SMTP server, but it's not recommended for production.
      delegate_to: localhost # The email sending happens from the Ansible control node
      no_log: true # Prevent sensitive information (like password) from appearing in logs
      # The 'mail' module sends the email from the machine where Ansible is run (control node).

    - name: Report email sending status
      ansible.builtin.debug:
        msg: "System report for {{ ansible_hostname }} sent to {{ mail_to }}."
