---
- name: Lookup DNS host from EE
  hosts: all
  connection: local
  gather_facts: false
  become: false
  tasks:

    - name: Lookup multiple names at once (from list variable)
      ansible.builtin.debug:
        msg: "A record found {{ item }}"
      loop: "{{ query('community.general.dig', *hosts) }}"
      vars:
        hosts:
          - example.org.
          - example.com.
          - gmail.com.


    - name: Resolve DNS Entries
      ansible.builtin.set_fact:
        dns_resolution: "{{ lookup('community.general.dig', DNS_ENTRY | default('example.com')) | split(',') }}"
      
    - name: "The TXT record for example.org."
      loop: "{{ dns_resolution }}"
      ansible.builtin.debug:
        msg: "{{ item }}"
        # msg: "{{ lookup('community.general.dig', DNS_ENTRY | default('example.com')) }}"
