---
- name: Use a vault file
  hosts: localhost
  gather_facts: false
  vars_files:
    - ./vault1.yml
    - ./vault2.yml

  tasks:
    - name: print out a variable
      ansible.builtin.debug:
        var: "thing1_key: {{ thing1_value }}"

    - name: print out a variable
      ansible.builtin.debug:
        var: "thing2_key: {{ thing2_value }}"
