---
- name: Install Security Patches
  hosts: "{{ _host }}"
  become: true
  gather_facts: true
  vars:
    allow_reboot: true 

  tasks:
    - name: Get packages
      ansible.builtin.package_facts:
      check_mode: false

    - name: Get services
      ansible.builtin.service_facts:
      check_mode: false

    - name: RedHat Security Updates execution block
      when: ansible_os_family == "RedHat"
      block:
        - name: Upgrade all security related packages (yum)
          when: ansible_pkg_mgr == "yum"
          ansible.builtin.yum:
            name: '*'
            security: true
            state: latest
            exclude: "{{ exclude_packages }}"
          register: patchingresult_yum

        - name: Upgrade all security related packages (dnf)
          when: ansible_pkg_mgr == "dnf"
          ansible.builtin.dnf:
            name: '*'
            security: true
            state: latest
            exclude: "{{ exclude_packages }}"
          register: patchingresult_dnf
    
        - name: Check to see if we need a reboot
          register: needs_restarting
          ansible.builtin.command: "dnf needs-restarting -r -s"
          changed_when: needs_restarting.rc == 1
          failed_when: needs_restarting.rc > 1
          notify: Reboot host
          check_mode: false

        - name: Reboot Server if Necessary
          ansible.builtin.reboot:
          when:
            - needs_restarting.rc == 1
            - allow_reboot
