---

- name: apply yum security updates to all nodes
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: Upgrade all security related packages
    yum:
      name: '*'
      security: yes
      state: latest
      #exclude: kernel*,foo*
    tags:
    - security

  tasks:
  - name: Upgrade all errata required packages
    yum:
      name: '*'
      bugfix: yes
      state: latest
    tags:
    - bugfix
