---

- name: apply yum security updates to all nodes
  hosts: all
  gather_facts: false
  remote_user: ansible
  become: true

  tasks:
  - name: Update yum cache
    yum:
      update_cache: yes
    tags:
    - bugfix
    - security

  - name: Upgrade all security related packages
    yum:
      name: '*'
      security: yes
      state: latest
      #exclude: kernel*,foo*
    tags:
    - security

  tasks:
  - name: Upgrade all errata required packages
    yum:
      name: '*'
      bugfix: yes
      state: latest
    tags:
    - bugfix
