---
- name: Run platform-specific patch application
  ansible.builtin.include_tasks:
    file: "{{ 'linux' if ansible_facts.os_family != 'Windows' else 'windows' }}.yml"

- name: Run shared patch summary
  ansible.builtin.include_tasks: shared.yml
