---
all:
  children:
    tomcat_windows:
      hosts:
        tomcat-win01.example.com:
        tomcat-win02.example.com:
      vars:
        ansible_connection: winrm
        ansible_winrm_transport: kerberos
        ansible_port: 5986
        ansible_winrm_server_cert_validation: validate
