---
- name: Playbook to show nodes on the failure recovery track of the workflow
  hosts: "{{ failure_nodes }}"
  gather_facts: false
  tasks:
    - name: Print out nodes on the recovery track
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }} is on the recovery track"