---
- name: Playbook to show success nodes in a failure scenario
  hosts: "{{ combined_success_nodes }}"
  gather_facts: false
  tasks:
    - name: Print out inventory_hostname
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }} is on the success track"