---
on: push

jobs:
  automation_controller_job:
    runs-on: ubuntu-latest
    name: Kick off Automation controller job
    steps:
      - name: AAP Automation Controller Action
        id: controller_job
        uses: ansible-cloud/aap_controller_action@v3.0.5
        #uses: ansible-cloud/aap_controller_action@v1.2.8
        with:
          controller_host: ${{ secrets.CONTROLLER_HOST }}
          controller_username: ${{ secrets.CONTROLLER_USERNAME }}
          controller_password: ${{ secrets.CONTROLLER_PASSWORD }}
          job_template: "Test Github Actions"
          extra_vars: "_survey_var=aws-rhel8"
          validate_certs: false
        env:
          pull_request_event: ${{ github.event.pull_request.number }}
